# **Практическое занятие 1: привыкаем к среде и переменным**

## **План семинара**
- Короткое введение
- Как будет устроено занятие?
- Чего мы хотим добиться сегодня?
- Тезисно вспоминаем основные понятия с лекции
    - Вопросы?
- Расходимся по комнатам:
    1. В первую очередь разбираемся с тем у кого не получилось установить анаконду
    2. Разбираемся с вопросами по `jupyter notebook`
    3. Разбираемся с простыми вопросами
    4. Остальные вопросы в порядке очереди
- Подводим итоги

## **Основные понятия с лекции**

### `jupyter notebook`

- Мы — в `jupyter notebook`
- Структурные элементы называются ячейками
- Эта ячейка с `markdown` — [текстовым языком разметки]((https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet))
- Ниже есть ячейки с кодом
- Запускать ячейки с кодом надо с помощью треугольничка сверху, выглядит как кнопка play
- Можно нажать `Ctrl + Enter`, выбрав нужную ячейку

In [ ]:
print('Hello world') # символы после решетки не считаются и называются комментарием

### Переменные

- Нужны для хранения информации
- Бывают разные типов:
    - `int` или `integer`: для хранения целых чисел
    - `bool`: для хранения `True` или `False`
    - `float`: для хранения нецелых чисел
    - `string`: для хранения строк (символов или слов)
    - Других типов
- Хранятся в памяти `python` если инициализированы (выполнен код где определяется переменная)

In [2]:
a = 3
b = True
c = 3.14
d = 'Доктор это вам'

In [4]:
print('Значение переменной a:', a, 'Тип переменной a:', type(a))
print('Значение переменной b:', b, 'Тип переменной b:', type(b))
print('Значение переменной c:', c, 'Тип переменной c:', type(c))
print('Значение переменной d:', d, 'Тип переменной d:', type(d))

Значение переменной a: 3 Тип переменной a: <class 'int'>
Значение переменной b: True Тип переменной b: <class 'bool'>
Значение переменной c: 3.14 Тип переменной c: <class 'float'>
Значение переменной d: Доктор это вам Тип переменной d: <class 'str'>

### Операции над переменными

- Основные операторы:
    - `+`
    - `-`
    - `/`
    - `*`
- Операторы сравнения (как результат возвращают тип `bool`):
    -  `>` - больше, `>=` - больше или равно
    -  `<` - меньше, `<=` - меньше или равно
    -  `==` - проверка равенства (возрващает два если значение одинаково)
    -  `!=` - не равно
- Логические операторы:
    - `and`
    - `or`
    - `not`
- **Дополнительные операторы** (забыл рассказать на лекции, но сейчас будут нам нужны):
    - `x**n` - `x` в степени `n`
    - `//` - деление нацело
    - `%` - остаток от деления

In [21]:
print('10 + 2 =', 10 + 2)
print('10 - 2 =', 10 - 2)
print('10/2 =', 10/2) # обратите внимание что результат уже не integer
print('10*2 =', 10*2)
print('10 > 2 =', 10 > 2)
print('10 < 2 =', 10 < 2)
print('10 == 2 =', 10 == 2)
print('10 != 2 =', 10 != 2)
print('True and False:', True and False)
print('True or False:', True or False)
print('not True:', not True)
print('2**3 =', 2**3)
print('9 // 4 =', 9 // 4)
print('9 % 4 =', 9 % 4)

10 + 2 = 12
10 - 2 = 8
10/2 = 5.0
10*2 = 20
10 > 2 = True
10 < 2 = False
10 == 2 = False
10 != 2 = True
True and False: False
True or False: True
not True: False
2**3 = 8
9 // 4 = 2
9 % 4 = 1

### Условные операторы:

- оператор `if` позволяет выполнять блок кода при выполнении условия
- следующая конструкция:
    - `if` + условие + :
    - (отступ) Блок кода
    - Блок кода вне отступа выполняется без условий
- `else`: блок кода, который будет выполняться если условие не выполнилось

In [23]:
number = 5 # можно поменять число

if number//2:
    print('Число четное')
else:
    print('Число нечетное')

Число четное

##  **Вопросы?**

## **Задания**

### Актерское мастерство

Помогите актеру завершить фразу! Он уже сказал часть фразы, но совсем забыл конец. В сценарии к пьесе его строка звучит так:
> Волобуев! Вот ваш меч!

Вам нужно вывести с помощью `print` полную фразу сложив две строки:

In [ ]:
start = 'Волбуев! Вот ваш'
finish = 

# Ваш код

### А число четное?

Выше мы уже проверяли четное ли число с помощью оператора `//`. Можем ли мы проверить это с помощью другого оператора?

In [ ]:
number = 5 

if *впишите условие*:
    print('Число четное')
else:
    print('Число нечетное')

### Очень условные операторы

Попробуйте написать программу, которая будет выводить на экран (с помощью `print`) число только если оно четное и больше 5

In [ ]:
number = 

# Ваш код

### Формула шаурмы

В киоске в Долгопрудном продается шаурма. Зная стоимость классической шаурмы и количество заказов, посчитайте стоимость заказа.

In [ ]:
price_vanilla = 180 # рублей
n = 3
price_total = # Ваш код

Зная предыдущие параметры, выведите сообщение с помощью команды `print` подставив туда настоящие числа:
> Стоимость шаурмы `цена` рублей. Вы заказали `количество` штук, с вас: `столько` рублей.

In [ ]:
# Ваше решение

✨ Студент физтеха приходит покупать шаурму за наличные деньги, но у него денег без сдачи. Посчитайте его сдачу и выведите сообщение:
> Стоимость шаурмы `цена` рублей. Вы заказали `количество` штук, с вас: `столько` рублей. Вы дали `вот столько` рублей, ваша сдача: `мяу` рублей.

In [ ]:
price_vanilla = 180 # рублей
n = 3
cash = 1000 # рублей

## Ой... чего-то у меня не работает...

Попробуйте понять, где студент Василий ошибся при программировании:

In [31]:
i = 2 
if i > 1:
print(i)

IndentationError: expected an indented block after 'if' statement on line 2 (986866140.py, line 3)

<p>
<details>
<summary> <u> Перевод ошибки: </u> </summary>

``` python
Ячейка In[31], строчка 3
    print(i)
    ^
ОшибкаОтступа: ожидался блок отсутпа после условия 'if' на строчке 2
```
</details>
</p>

Исправьте ошибку студента Василия:

In [ ]:
# Ваш код

Студент Евгений пришел после работы ночным грузчиком на пару по программированию. Он писал код, сделал ошибку, а теперь сидит, смотрит в экран и не понимает что с ней делать. Как нам помочь Евгению?

In [33]:
rate = 10 
time = 200

print('Всего:' rate*total)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (890468006.py, line 4)

<p>
<details>
<summary> <u> Перевод ошибки: </u> </summary>

``` python
  Ячейка In[33], строчка 4
    print('Всего:' rate*total)
          ^
СинтаксическаяОшибка: неверный синтаксис. Может вы забыли запятую?
```
</details>
</p>

Помогите Евгению:

In [ ]:
# Ваш код

### Котик Томас

Черный кот Томас очень любит спать весь день, а хозяйка кота Томаса очень любит с ним играть. Чтобы Томас высыпался, ему нужно чтобы время игры в год не превышало `30 000` минут. Хозяйка может играть с котом Томасом:
- `63` минуты в рабочий день
- `127` минут в выходной

Напишите программу, которая по количеству выходных в году определяет, будет ли высыпаться кот Томас. В году 365 дней.

In [ ]:
n_holidays = 25

# Ваш код

✨ Посчитайте разницу между нормой сна Томаса и получившимся количеством в часах и минутах:

In [ ]:
# Ваш код

### Интересное государство когда-нибудь

В одной стране решили ввести прогрессивную шкалу подходного налога. Шкала выглядит так:
- Налог 0% если доход меньше 1 миллиона фантиков в год
- Налог 12% если доход больше 1 миллиона фантиков в год
- Налог 25% если доход больше 5 миллиона фантиков в год
- Налог 50% если доход больше 20 миллионов фантиков в год

Реализуйте алгоритм подсчета налогов в зависимость от оплаты в месяц граждан этой страны. Посчитайте доход после вычета налогов для месячной зарплаты в `30 000`, `80 000`, `160 000`, `500 000`, `2 000 000` фантиков в месяц:

In [ ]:
salary = 

# Ваш код

✨ Гражданин этой страны узнает, что заплатив около `500 000` фантиков в год можно перенести 3/4 своего дохода в маленькую страну с другой ставкой налогобложения (5%). Для заданных сверху зарплат, кто получит выгоду от этой `схемы`?

In [ ]:
# Ваш код

### ✨ А годы идут

Напишите алгоритм, который зная год, узнает високосный он или нет. Чтобы узнать как опредить високосный год, воспользуйтесь поисковиком (я тоже не знал).

In [ ]:
# Ваш код

### ✨✨ Цифры цифры цифирки 

Напишите алгоритм который выводит каждую цифру четырехзначного числа отдельно. Пользуйтесь **только** знаниями полученными на этом курсе раннее. Нельзя использовать индексирование строк.

In [30]:
number = 1377

# Ваш код

### ✨✨ Глобальное потепление

Турист пытается пересечь некое расстояние выделяя наименьшее количество парниковых газов (эквивалент CO$_2$. Ему доступны следующие моды передвижения:
- Пешком: 0 CO$_2$ за километр, но не более 5 км
- Велосипед: 0.005 CO$_2$ за километр, но не более 15 км
- Автобус: 0.1 CO$_2$ за километр, но не более 80 км
- Поезд: 0.005 CO$_2$ за километр, но только число кратное 100 км

Напишите алгоритм, который позволит вычислять минимальное количество CO$_2$ за поездку. Пользуйтесь только знаниями полученными на этом курсе раннее.


Посчитайте минимальное количество CO$_2$, которое выделит турист за поездки в:
- `31` км
- `74` км
- `160` км
- `1350` км

In [ ]:
# Ваш код

## Использованные ресурсы:
Задачи про кота Томаса и про глобальное потепление были вдохновлены [этим учебником на английском](https://python-book.softuni.org/chapter-03-simple-conditions-exam-problems.html).